
services:
  overpass:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: overpass
    volumes:
      - ./overpass_db:/usr/local/overpass_db
    expose:
      - "9000"
    networks:
      - overpass-net

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: overpass-nginx
    env_file:
      - ./.env
    depends_on:
      - overpass
    ports:
      - "80:80"
      - "443:443"
    networks:
      - overpass-net
    secrets:
      - overpass_api_keys
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - API_KEYS_FILE=/run/secrets/overpass_api_keys

networks:
  overpass-net:
    driver: bridge

secrets:
  overpass_api_keys:
    file: ./secrets/api_keys.txt
